name: Build and deploy an app to AKS with Helm
"on":
  push:
    branches:
    - $default-branch
  workflow_dispatch: null
env:
  AZURE_CONTAINER_REGISTRY: izroll
  CHART_OVERRIDE_PATH: ./charts/values.yaml
  CHART_PATH: ./charts
  CLUSTER_NAME: krustlet
  CONTAINER_NAME: contoso
  RESOURCE_GROUP: izroll-dev
jobs:
  build:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    - name: Build and push image to ACR
      run: |
        az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}
    - name: Attach ACR to AKS cluster
      run: |
        az aks update -n ${{ env.CLUSTER_NAME }} -g ${{ env.RESOURCE_GROUP }} --attach-acr ${{ env.AZURE_CONTAINER_REGISTRY }}
    - id: bake
      name: Bake deployment
      uses: azure/k8s-bake@v2.1
      with:
        helm-version: latest
        helmChart: ${{ env.CHART_PATH }}
        overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
        overrides: |
          replicas:2
        renderEngine: helm
    - name: Deploy application
      uses: Azure/k8s-deploy@v3.0
      with:
        action: deploy
        images: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
